name: test and release

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
        branches: [main]
        inputs:
            force-release:
                default: false
                description: "try to release even with no changes"
                required: false
                type: boolean

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x]
        steps:
            - uses: actions/checkout@v2
            - name: setup node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: yarn test --coverage
    release:
        runs-on: ubuntu-latest
        needs: [test]
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v2
            - name: setup node ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: |
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git config user.name "github-actions[bot]"
                npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
                yarn release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
